### ISSUE TITLE
Build Routes for Categories API

### ISSUE THREAD

**Issue by Mac-lp3** [yadaguru/yadaguru-api#16]
Assign the task to yourself once you begin building...

**Comment by bobderrico80** [comment]
I want to bring up for discussion the response for POST/PUT/DELETE requests. My thought would be to return the current set of items for the model after it is updated.

For example: I have two categories, 'foo', and 'bar'. I POST to /api/categories/ and a third category 'bazz'. As a response, I get an array of objects containing categories 'foo', 'bar', and 'bazz'.

I like this approach, because it make it easy to keep things in sync in the front end. We add a new school, for example, and when the response comes back in, we just update the value of `$scope.schools`, with the response.

What do you think?

**Comment by Mac-lp3** [comment]
That does sound like an easy way to keep things up to date.

In my experience, we have always just returned the object which we created via POST/PUT. So if you were to POST the `/bike` collection, you would get back a single bike, and if you did a PUT on the `/bike` collection with an array (composed of a subset of the bikes collection, which had some change), you would get back that array of the bikes.

Again, this is just what I am used to. My only worry about getting all of a collection back on a POST/PUT is around how big those collections are expected to get. If the collections are bound to stay manageable I don't see why it would be a problem and might save a bit of time for the user.

Also, if you have not seen it, I developers in my company consider the [Apigee REST API talk](https://www.youtube.com/watch?v=QpAhXa12xvU) to be industry standard on REST. It was pretty interesting when it came out and I still refer to it some times. Hope you guys can get something out of it.

**Comment by bobderrico80** [comment]
That's definitely a good point about the collections getting unmanageable. There could be a trade-off there. I will definitely check out the talk. Thanks for sharing!
